#!/bin/bash
# A script that displays the custom commands that are available

echo "  Commands:"
echo ""
echo "  1pass   =  1Password commands."
echo "  crypto  =  File encryption commands."
echo "  plex    =  PlexMediaServer commands."
echo "  sysoff  =  System shutdown commands."
echo "  tomcat  =  Tomcat Server commands."