#!/bin/bash
# Script to encrypt/decrypt files

ENCRYPT="encrypt"
DECRYPT="decrypt"
AES128="AES128"
AES256="AES256"

function main {
	case $1 in
		e) operation=$ENCRYPT ;;
		d) operation=$DECRYPT ;;
		*)
			echo "Error! Invalid input!"
			exit 1
		;;
	esac

	if [[ $operation == $ENCRYPT ]]; then
		echo "Algorithms"
		echo "  1) AES-128"
		echo "  2) AES-256"
		read -p "Choose algorithm: "
		case $REPLY in
			1) algorithm=$AES128 ;;
			2) algorithm=$AES256 ;;
			*)
				echo "Error! Invalid selection"
				exit 1
			;;
		esac
	fi

	read -p "File to $operation: "
	inputFile=$REPLY
	if [[ ! -f $inputFile ]]; then
		echo "Error! File to $operation does not exist!"
		exit 1
	fi

	read -p "Output file: "
	outputFile=$REPLY

	case $operation in
		$ENCRYPT) gpg2 --output $outputFile --symmetric --cipher-algo $algorithm $inputFile ;;
		$DECRYPT) gpg2 --output $outputFile --decrypt $inputFile ;;
		*)
			echo "Error! Invalid operation setting: $operation"
			exit 1
		;;
	esac
}

function script_help {
	echo "  Cryptography Commands:"
	echo ""
	echo "  e  =  Encrypt a specified file."
	echo "  d  =  Decrypt a specified file."
}

if [[ $# -lt 1 ]]; then
	script_help
	exit 0
fi

if [[ $# -gt 1 ]]; then
	echo "Error! Invalid number of arguments: $#"
	exit 1
fi

main $1