#!/bin/bash
# PilotFish FTP shortcuts

function main {

	case $1 in
		adriatic) ftp adriatic.pilotfish-net.com ;;
		slipstream) ftp adriatic.pilotfish-net.com ;;
		release) ftp perch.pilotfish-net.com ;;
		*)
			echo "Error! Invalid argument: $1"
			exit 1
		;;
	esac

}

function script_help {
	echo "  PilotFish FTP Servers"
	echo ""
	echo "  adriatic    =  The main FTP server for storing general files"
	echo "  slipstream  =  The FTP server where the slipstream builds are located"
	echo "  release     =  The FTP server where the latest release builds are located"
}

if [[ $# -lt 1 ]]; then
	script_help
	exit 0
fi

if [[ $# -gt 1 ]]; then
	echo "Error! Invalid number of arguments: $#"
	exit 1
fi

main $1